import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import {
  FormControl,
  InputGroup,
  ListGroup,
  Form,
  Button,
} from "react-bootstrap";

export default function Home() {
  const [members, setMembers] = useState([]);
  const [name, setName] = useState("");
  const [location, setLocation] = useState("");
  const [github, setGitHub] = useState("");
  const [keyword, setKeyword] = useState("");

  useEffect(() => {
    fetch("http://localhost:3000/api/members")
      .then((response) => response.json())
      .then((members) => setMembers(members));
  }, []);

  const submitSave = (e) => {
    e.preventDefault();
    fetch("http://localhost:3000/api/members", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name, location, github }),
    })
      .then((response) => response.json())
      .then((member) => setMembers(members.concat(member)));
  };

  const submitSearch = (e) => {
    e.preventDefault();
    fetch(`http://localhost:3000/api/members?keyword=${keyword}`)
      .then((response) => response.json())
      .then((members) => setMembers(members));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form inline>
          <InputGroup>
            <FormControl
              type="text"
              placeholder="Keyword"
              onChange={(e) => setKeyword(e.target.value)}
            />
            <InputGroup.Append>
              <Button variant="outline-secondary" onClick={submitSearch}>
                Search
              </Button>
            </InputGroup.Append>
          </InputGroup>
        </Form>

        <h1 className={styles.title}>Welcome to EddieHub!</h1>

        <Form inline>
          <InputGroup>
            <FormControl
              type="text"
              placeholder="Name"
              onChange={(e) => setName(e.target.value)}
            />
            <FormControl
              type="text"
              placeholder="Location"
              onChange={(e) => setLocation(e.target.value)}
            />
            <FormControl
              type="text"
              placeholder="GitHub"
              onChange={(e) => setGitHub(e.target.value)}
            />
            <InputGroup.Append>
              <Button variant="outline-secondary" onClick={submitSave}>
                Save
              </Button>
            </InputGroup.Append>
          </InputGroup>
        </Form>

        <ListGroup>
          {members.map((member) => (
            <ListGroup.Item key={member.id}>
              {member.name}, {member.location}, {member.github}
            </ListGroup.Item>
          ))}
        </ListGroup>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
